[package]
name = "stravant/roblox-materialflip"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
createSharedToolbar = "stravant/create-shared-toolbar@0.1.0"